[build]
command = """
  mkdir -p $HOME/.java &&
  cd $HOME/.java &&
  wget -O openjdk.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8+7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.8_7.tar.gz &&
  tar -xzf openjdk.tar.gz &&
  rm openjdk.tar.gz &&
  export JAVA_HOME=$HOME/.java/jdk-17.0.8+7 &&
  export PATH=$JAVA_HOME/bin:$PATH &&
  java -version &&
  cd /opt/build/repo &&

  bash ./gradlew -Pvaadin.productionMode=true bootJar
  cd /build/libs &&
  java -jar GRC-0.0.1.jar
"""

