

[build]
command = "mkdir -p $HOME/.java && cd $HOME/.java && wget -O openjdk.tar.gz https://github.com/adoptium/temurin17-binaries/releases/latest/download/OpenJDK17U-jdk_x64_linux_hotspot.tar.gz && tar -xzf openjdk.tar.gz && rm openjdk.tar.gz && export JAVA_HOME=$HOME/.java/jdk-17 && export PATH=$JAVA_HOME/bin:$PATH && java -version && bash gradlew -Pvaadin.productionMode=true bootJar"

